// Auto-generated by: npx supabase gen types typescript --project-id YOUR_PROJECT_ID
// Run after applying migrations to regenerate

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type UserRole = 'admin' | 'staff' | 'mentor' | 'educator' | 'client' | 'minor'
export type DivisionType = 'football' | 'fitness' | 'sports'
export type BookingType = 'contracted' | 'one_on_one' | 'group_public' | 'group_private'
export type BookingStatus = 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'no_show'
export type ContentType = 'video' | 'document' | 'live_session'
export type CreditTxType = 'deposit' | 'booking_payment' | 'refund_full' | 'refund_partial' | 'manual_adjustment' | 'bonus'
export type CancellationReason = 'client_notice' | 'client_breach' | 'staff_cancelled' | 'no_show'

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: UserRole
          phone: string | null
          date_of_birth: string | null
          parent_guardian_id: string | null
          tier_id: string | null
          credit_balance_p: number
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Partial<Database['public']['Tables']['profiles']['Row']> & { id: string; email: string }
        Update: Partial<Database['public']['Tables']['profiles']['Row']>
      }
      tiers: {
        Row: {
          id: string
          name: string
          description: string | null
          features: Json
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['tiers']['Row']> & { name: string; features: Json }
        Update: Partial<Database['public']['Tables']['tiers']['Row']>
      }
      divisions: {
        Row: {
          id: string
          slug: DivisionType
          name: string
          color_hex: string
          tagline: string | null
          description: string | null
          is_active: boolean
        }
        Insert: Partial<Database['public']['Tables']['divisions']['Row']> & { slug: DivisionType; name: string; color_hex: string }
        Update: Partial<Database['public']['Tables']['divisions']['Row']>
      }
      user_divisions: {
        Row: { user_id: string; division_id: string; enrolled_at: string }
        Insert: { user_id: string; division_id: string; enrolled_at?: string }
        Update: Partial<Database['public']['Tables']['user_divisions']['Row']>
      }
      staff_availability: {
        Row: {
          id: string
          staff_id: string
          day_of_week: number | null
          start_time: string | null
          end_time: string | null
          specific_date: string | null
          specific_start: string | null
          specific_end: string | null
          buffer_mins: number
          max_clients: number
          is_active: boolean
          created_at: string
        }
        Insert: Partial<Database['public']['Tables']['staff_availability']['Row']> & { staff_id: string }
        Update: Partial<Database['public']['Tables']['staff_availability']['Row']>
      }
      bookings: {
        Row: {
          id: string
          client_id: string
          staff_id: string | null
          division_id: string | null
          booking_type: BookingType
          status: BookingStatus
          starts_at: string
          ends_at: string
          duration_mins: number
          deposit_p: number
          total_cost_p: number
          credits_used_p: number
          contract_weeks: number | null
          contract_notes: string | null
          group_class_id: string | null
          notes: string | null
          cancelled_at: string | null
          cancellation_reason: CancellationReason | null
          no_show_at: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Partial<Database['public']['Tables']['bookings']['Row']> & {
          client_id: string; booking_type: BookingType; starts_at: string; ends_at: string; duration_mins: number
        }
        Update: Partial<Database['public']['Tables']['bookings']['Row']>
      }
      group_classes: {
        Row: {
          id: string
          title: string
          description: string | null
          instructor_id: string
          division_id: string | null
          is_public: boolean
          max_participants: number
          starts_at: string
          ends_at: string
          location: string | null
          cost_p: number
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Partial<Database['public']['Tables']['group_classes']['Row']> & {
          title: string; instructor_id: string; starts_at: string; ends_at: string
        }
        Update: Partial<Database['public']['Tables']['group_classes']['Row']>
      }
      credit_transactions: {
        Row: {
          id: string
          user_id: string
          tx_type: CreditTxType
          amount_p: number
          balance_after_p: number
          booking_id: string | null
          description: string | null
          created_by: string | null
          created_at: string
        }
        Insert: Partial<Database['public']['Tables']['credit_transactions']['Row']> & {
          user_id: string; tx_type: CreditTxType; amount_p: number; balance_after_p: number
        }
        Update: never
      }
      goals: {
        Row: {
          id: string
          player_id: string
          set_by_id: string
          title: string
          description: string | null
          category: string
          target_value: number | null
          current_value: number
          unit: string | null
          target_date: string | null
          completed_at: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['goals']['Row']> & {
          player_id: string; set_by_id: string; title: string
        }
        Update: Partial<Database['public']['Tables']['goals']['Row']>
      }
      performance_entries: {
        Row: {
          id: string
          player_id: string
          booking_id: string | null
          division_id: string | null
          recorded_by: string
          metrics: Json
          notes: string | null
          recorded_at: string
        }
        Insert: Partial<Database['public']['Tables']['performance_entries']['Row']> & {
          player_id: string; recorded_by: string; metrics: Json
        }
        Update: Partial<Database['public']['Tables']['performance_entries']['Row']>
      }
      education_content: {
        Row: {
          id: string
          title: string
          description: string | null
          content_type: ContentType
          division_id: string | null
          url: string | null
          duration_mins: number | null
          is_free: boolean
          order_index: number
          published_at: string | null
          created_by: string
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: Partial<Database['public']['Tables']['education_content']['Row']> & {
          title: string; content_type: ContentType; created_by: string
        }
        Update: Partial<Database['public']['Tables']['education_content']['Row']>
      }
      education_progress: {
        Row: {
          id: string
          user_id: string
          content_id: string
          progress_pct: number
          completed_at: string | null
          last_accessed: string
        }
        Insert: Partial<Database['public']['Tables']['education_progress']['Row']> & {
          user_id: string; content_id: string
        }
        Update: Partial<Database['public']['Tables']['education_progress']['Row']>
      }
      client_assignments: {
        Row: {
          staff_id: string
          client_id: string
          division_id: string | null
          assigned_at: string
          is_active: boolean
        }
        Insert: { staff_id: string; client_id: string; division_id?: string | null; is_active?: boolean }
        Update: Partial<Database['public']['Tables']['client_assignments']['Row']>
      }
    }
    Views: Record<string, never>
    Functions: {
      deduct_credits: {
        Args: { p_user_id: string; p_amount_p: number; p_description: string; p_booking_id?: string }
        Returns: number
      }
      add_credits: {
        Args: { p_user_id: string; p_amount_p: number; p_tx_type: CreditTxType; p_description: string; p_booking_id?: string; p_created_by?: string }
        Returns: number
      }
    }
    Enums: {
      user_role: UserRole
      division_type: DivisionType
      booking_type: BookingType
      booking_status: BookingStatus
      content_type: ContentType
      credit_tx_type: CreditTxType
      cancellation_reason: CancellationReason
    }
  }
}
